src/Web/Pages/ShoppingLists/Details.cshtml.cs
using ApplicationServices.Operations;
using ApplicationServices.ShoppingLists;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Operations.Dtos.PaymentRecords;
using Operations.Entities;
using ShoppingLists.Dtos;
using ShoppingLists.Entities;

namespace Web.Pages.ShoppingLists;

public class DetailsModel : PageModel
{
    private readonly IShoppingListsService _shoppingListsService;
    private readonly IOperationsService _operationsService;

    public DetailsModel(IShoppingListsService shoppingListsService, IOperationsService operationsService)
    {
        _shoppingListsService = shoppingListsService;
        _operationsService = operationsService;
    }

    public ShoppingList ShoppingList { get; private set; }
    
    public List<Card> AllCards { get; private set; }
    
    public async Task<IActionResult> OnGet(Guid id)
    {
        var shoppingList = await _shoppingListsService.GetShoppingListWithItems(User, id);
        var userCards = await _operationsService.GetAllUserCards(User);
        
        ShoppingList = shoppingList;
        ShoppingList.ListItems = shoppingList?.ListItems.OrderBy(item => item.CreationTime).ToList();
        AllCards = userCards?.OrderBy(card => card.Name).ToList();
        
        return Page();
    }

    public async Task<IActionResult> OnPostListItem(CreateListItemDto dto)
    {
        await _shoppingListsService.CreateListItem(User, dto);

        return RedirectToPage(new {id = dto.ShoppingListId});
    }

    public async Task<IActionResult> OnPostPurchase(Guid listId, Guid itemId)
    {
        await _shoppingListsService.PurchaseListItem(User, itemId);

        return RedirectToPage(new {id = listId});
    }
    
    public async Task<IActionResult> OnPostCancelPurchase(Guid listId, Guid itemId)
    {
        await _shoppingListsService.CancelPurchaseListItem(User, itemId);

        return RedirectToPage(new {id = listId});
    }

    public async Task<IActionResult> OnPostToOperations(CreatePaymentRecordDto recordDto)
    {
        await _operationsService.CreatePayment(User, recordDto);

        return RedirectToPage(new {id = recordDto.ListId});
    }

    public async Task<IActionResult> OnPostUpdateListItem(UpdateListItemDto dto)
    {
        await _shoppingListsService.UpdateListItem(User, dto);

        return RedirectToPage(new {id = dto.ListId});
    }

    public async Task<IActionResult> OnPostDeleteListItem(Guid listId, Guid itemId)
    {
        await _shoppingListsService.DeleteListItem(User, itemId);

        return RedirectToPage(new {id = listId});
    }
}

src/Web/Pages/ShoppingLists/Index.cshtml.cs
using ApplicationServices.Operations;
using ApplicationServices.ShoppingLists;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Operations.Dtos;
using Operations.Entities;
using ShoppingLists.Dtos;
using ShoppingLists.Entities;

namespace Web.Pages.ShoppingLists;

public class IndexModel : PageModel
{
    private readonly IShoppingListsService _shoppingListsService;
    private readonly IOperationsService _operationsService;

    public IndexModel(IShoppingListsService shoppingListsService, IOperationsService operationsService)
    {
        _shoppingListsService = shoppingListsService;
        _operationsService = operationsService;
    }
    
    public List<ShoppingList> ShoppingListsWithItems { get; private set; }
    
    public List<Card> AllCards { get; private set; }

    public async Task<IActionResult> OnGet()
    {
        var shoppingListsWithItems = await _shoppingListsService.GetAllUserShoppingListsWithItems(User);
        var userCards = await _operationsService.GetAllUserCards(User);

        ShoppingListsWithItems = shoppingListsWithItems?.OrderByDescending(list => list.CreationTime).ToList();
        AllCards = userCards?.OrderBy(card => card.Name).ToList();

        return Page();
    }

    public async Task<IActionResult> OnPostShoppingList(CreateShoppingListDto dto)
    {
        await _shoppingListsService.CreateShoppingList(User, dto);
        
        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostToOperations(CreatePaymentDto dto)
    {
        await _operationsService.CreatePayment(User, dto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostUpdateShoppingList(UpdateShoppingListDto dto)
    {
        await _shoppingListsService.UpdateShoppingList(User, dto);
        
        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostDeleteShoppingList(Guid id)
    {
        await _shoppingListsService.DeleteShoppingList(User, id);
        
        return RedirectToPage();
    }
}

src/Web/Pages/ShoppingLists/AddListItemPartial.cshtml
@model Guid

<div class="modal fade" id="addListItemModal" tabindex="-1" aria-labelledby="addListItemModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" asp-page-handler="ListItem">
                <div class="modal-header">
                    <h5 class="modal-title" id="addListItemModalLabel">Add List Item</h5>
                    <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="addListItemName" class="form-label">Name</label>
                        <input type="text" class="form-control input-dark" id="addListItemName" name="name" autocomplete="off">
                    </div>
                    <div class="mb-3">
                        <label for="addListItemPrice" class="form-label">Price</label>
                        <input type="number" class="form-control input-dark" id="addListItemPrice" name="price" autocomplete="off" step="0.01" min="0">
                    </div>
                    <div class="mb-3">
                        <label for="addListItemCount" class="form-label">Count</label>
                        <input type="number" class="form-control input-dark" id="addListItemCount" name="count" autocomplete="off">
                    </div>
                    <input type="hidden" name="shoppingListId" value="@Model"/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-dark">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

src/Web/Pages/ShoppingLists/AddShoppingListPartial.cshtml
<div class="modal fade" id="addShoppingListModal" tabindex="-1" aria-labelledby="addShoppingListModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" asp-page-handler="ShoppingList">
                <div class="modal-header">
                    <h5 class="modal-title" id="addShoppingListModalLabel">Add Shopping List</h5>
                    <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="addShoppingListName" class="form-label">Name</label>
                        <input type="text" class="form-control input-dark" id="addShoppingListName" name="name" autocomplete="off">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-dark">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

src/Web/Pages/ShoppingLists/Details.cshtml
@page "{id}"
@model Web.Pages.ShoppingLists.DetailsModel

@{
    ViewData["Title"] = @Model.ShoppingList.Name;
}

<div class="fs-4 p-2">
    <a asp-page="/ShoppingLists/Index" class="text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-square-fill" viewBox="0 0 16 16" style="width: 1em; height: 1em; vertical-align: -0.125em">
                <path d="M16 14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12zm-4.5-6.5H5.707l2.147-2.146a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L5.707 8.5H11.5a.5.5 0 0 0 0-1z"></path>
        </svg>
        Back
    </a>
</div>

<div class="d-flex">
    <div class="p-2 fs-4">@Model.ShoppingList.Name, Sum: @Model.ShoppingList.ListItems.Sum(item => item.Price * item.Count)</div>
    <div class="p-2">
        <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#addListItemModal" style="width: 5rem;">
            Add
        </button>
    </div>
</div>

<div class="p-2">
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th class="col">Count</th>
            <th class="col">Sum</th>
            <th class="col"></th>
            <th class="col"></th>
            <th class="col"></th>
            <th class="col"></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.ShoppingList.ListItems)
        {
            <tr>
                <th scope="row">
                    @if (item.IsPurchased)
                    {
                        <input type="checkbox" class="form-check-input checkbox-dark" disabled checked/> 
                    }
                    else
                    {
                        <input type="checkbox" class="form-check-input checkbox-dark" disabled/> 
                    }
                </th>
                <td>@item.Name</td>
                <td>@item.Price</td>
                <td>@item.Count</td>
                <td>@(item.Price * item.Count)</td>
                <td>
                    <div>
                        @if (item.IsPurchased)
                        {
                            <form method="POST">
                                <button type="submit" class="btn btn-dark" asp-page-handler="CancelPurchase" asp-route-listId="@item.ShoppingListId" asp-route-itemId="@item.Id">Cancel Purchase</button>
                            </form>
                        }
                        else
                        {
                            <form method="POST">
                                <button type="submit" class="btn btn-dark" asp-page-handler="Purchase" asp-route-listId="@item.ShoppingListId" asp-route-itemId="@item.Id">Purchase</button>
                            </form>
                        }
                    </div>
                </td>
                <td>
                    <div>
                        <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#@string.Concat("toOperations", item.Id)">To Operations</button>
                    </div>
                </td>
                <td>
                    <div>
                        <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#@string.Concat("updateListItem", item.Id)">Update</button>
                    </div>
                </td>
                <td>
                    <div>
                        <form method="POST">
                            <button type="submit" class="btn btn-dark" asp-page-handler="DeleteListItem" asp-route-listId="@item.ShoppingListId" asp-route-itemId="@item.Id">Delete</button>
                        </form>
                    </div>
                </td>
            </tr>
    
            <partial name="UpdateListItemPartial" model="item"/>
            <partial name="ListItemToOperationsPartial" model="(item, Model.AllCards)"/>
        }
        </tbody>
    </table>
</div>

<partial name="AddListItemPartial" model="Model.ShoppingList.Id"/>

src/Web/Pages/ShoppingLists/Index.cshtml
@page
@model Web.Pages.ShoppingLists.IndexModel

@{
    ViewData["Title"] = "Shopping Lists";
}

<div class="d-flex mb-3">
    <div class="p-2 h4">Shopping Lists</div>
    <div class="p-2">
        <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#addShoppingListModal" style="width: 5rem;">
            Add
        </button>
    </div>
</div>

<div>
    @foreach (var shoppingList in Model.ShoppingListsWithItems)
    {
        <div class="card mb-2">
            <div class="card-body hstack gap-4">
                <div class="fs-5"><a asp-page="Details" asp-route-id="@shoppingList.Id">@shoppingList.Name</a></div>
                <div class="fs-5 ms-auto">Items: @shoppingList.ListItems.Count</div>
                <div class="fs-5">Sum: @shoppingList.ListItems.Sum(item => item.Price * item.Count)</div>
                <div class="fs-5">Created: @shoppingList.CreationTime</div>
                <div>
                    <button type="button" class="btn btn-dark" data-bs-toggle="offcanvas" data-bs-target="#@string.Concat("id", shoppingList.Id)" aria-controls="@string.Concat("id", shoppingList.Id)">
                        Preview
                    </button>
                </div>
                <div>
                    <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#@string.Concat("toOperations", shoppingList.Id)">To Operations</button>
                </div>
                <div>
                    <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#@string.Concat("updateShoppingList", shoppingList.Id)">Update</button>
                </div>
                <div>
                    <form method="POST">
                        <button type="submit" class="btn btn-dark" asp-page-handler="DeleteShoppingList" asp-route-id="@shoppingList.Id">Delete</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="@string.Concat("id", shoppingList.Id)" aria-labelledby="offcanvasScrollingLabel">
            <partial name="ShoppingListPreviewPartial" model="@shoppingList"/>
        </div>
        
        <partial name="ShoppingListToOperationsPartial" model="(shoppingList, Model.AllCards)"/>
        <partial name="UpdateShoppingListPartial" model="shoppingList"/>
    }
</div>

<partial name="AddShoppingListPartial"/>

src/Web/Pages/ShoppingLists/ListItemToOperationsPartial.cshtml
@using ListItem = global::ShoppingLists.Entities.ListItem
@using Card = global::Operations.Entities.Card
@model (ListItem, List<Card>)

<div class="modal fade" id="@string.Concat("toOperations", Model.Item1.Id)" tabindex="-1" aria-labelledby="toOperationsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" asp-page-handler="ToOperations">
                <div class="modal-header">
                    <h5 class="modal-title" id="toOperationsModalLabel">To Operations</h5>
                    <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control input-dark" id="name" name="name" autocomplete="off" value="@Model.Item1.Name">
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="form-label">Amount</label>
                        <input type="number" class="form-control input-dark" id="amount" name="amount" autocomplete="off" value="@(Model.Item1.Price * Model.Item1.Count)" step="0.01" min="0">
                    </div>
                    <div class="dropdown mb-3">
                        @* ReSharper disable once Html.IdDuplication *@
                        <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdownMenuClickableInside" data-bs-auto-close="outside">
                            Select cards
                        </button>
                        <div class="dropdown-menu p-2">
                            @foreach (var card in Model.Item2)
                            {
                                <div class="mb-1">
                                    <div class="form-check form-check-inline">
                                        <input type="radio" class="form-check-input checkbox-dark" id="card" name="cardId" value="@card.Id">
                                        <label class="form-check-label" for="card">
                                            @card.Name, balance: @card.Balance
                                        </label>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <input type="hidden" name="id" value="@Model.Item1.Id"/>
                    <input type="hidden" name="listId" value="@Model.Item1.ShoppingListId"/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-dark">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

src/Web/Pages/ShoppingLists/ShoppingListPreviewPartial.cshtml
@using global::ShoppingLists.Entities
@model ShoppingList

<div class="offcanvas-header">
    <h5 class="offcanvas-title">@Model.Name</h5>
    <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="offcanvas" aria-label="Close"></button>
</div>
<div class="offcanvas-body">
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Count</th>
            <th scope="col">Sum</th>
        </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ListItems)
            {
                <tr>
                    <th scope="row">
                        @if (item.IsPurchased)
                        {
                            <input type="checkbox" class="form-check-input checkbox-dark" checked disabled/> 
                        }
                        else
                        {
                            <input type="checkbox" class="form-check-input checkbox-dark" disabled/> 
                        }
                    </th>
                    <td>@item.Name</td>
                    <td>@item.Price</td>
                    <td>@item.Count</td>
                    <td>@(item.Price * item.Count)</td>
                </tr>
            }
        </tbody>
    </table>
</div>

src/Web/Pages/ShoppingLists/ShoppingListToOperationsPartial.cshtml
@using Card = global::Operations.Entities.Card
@using ShoppingList = global::ShoppingLists.Entities.ShoppingList
@model (ShoppingList, List<Card>)

<div class="modal fade" id="@string.Concat("toOperations", Model.Item1.Id)" tabindex="-1" aria-labelledby="toOperationsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" asp-page-handler="ToOperations">
                <div class="modal-header">
                    <h5 class="modal-title" id="toOperationsModalLabel">To Operations</h5>
                    <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control input-dark" id="name" name="name" autocomplete="off" value="@Model.Item1.Name">
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="form-label">Amount</label>
                        <input type="number" class="form-control input-dark" id="amount" name="amount" autocomplete="off" value="@(Model.Item1.ListItems.Sum(item => item.Price * item.Count))" step="0.01" min="0">
                    </div>
                    <div class="dropdown mb-3">
                        @* ReSharper disable once Html.IdDuplication *@
                        <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdownMenuClickableInside" data-bs-auto-close="outside">
                            Select cards
                        </button>
                        <div class="dropdown-menu p-2">
                            @foreach (var card in Model.Item2)
                            {
                                <div class="mb-1">
                                    <div class="form-check form-check-inline">
                                        <input type="radio" class="form-check-input checkbox-dark" id="card" name="cardId" value="@card.Id">
                                        <label class="form-check-label" for="card">
                                            @card.Name, balance: @card.Balance
                                        </label>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <input type="hidden" name="id" value="@Model.Item1.Id"/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-dark">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

src/Web/Pages/ShoppingLists/UpdateListItemPartial.cshtml
@using ListItem = global::ShoppingLists.Entities.ListItem
@model ListItem

<div class="modal fade" id="@string.Concat("updateListItem", Model.Id)" tabindex="-1" aria-labelledby="updateListItemModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" asp-page-handler="UpdateListItem">
                <div class="modal-header">
                    <h5 class="modal-title" id="updateListItemModalLabel">Update List Item</h5>
                    <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="updateListItemName" class="form-label">Name</label>
                        <input type="text" class="form-control input-dark" id="updateListItemName" name="name" autocomplete="off" value="@Model.Name">
                    </div>
                    <div class="mb-3">
                        <label for="updateListItemPrice" class="form-label">Price</label>
                        <input type="number" class="form-control input-dark" id="updateListItemPrice" name="price" autocomplete="off" value="@Model.Price" step="0.01" min="0">
                    </div>
                    <div class="mb-3">
                        <label for="updateListItemCount" class="form-label">Count</label>
                        <input type="number" class="form-control input-dark" id="updateListItemCount" name="count" autocomplete="off" value="@Model.Count">
                    </div>
                    <input type="hidden" name="id" value="@Model.Id"/>
                    <input type="hidden" name="listId" value="@Model.ShoppingListId"/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-dark">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

src/Web/Pages/ShoppingLists/UpdateShoppingListPartial.cshtml
@using ShoppingList = global::ShoppingLists.Entities.ShoppingList
@model ShoppingList


<div class="modal fade" id="@string.Concat("updateShoppingList", Model.Id)" tabindex="-1" aria-labelledby="updateShoppingListModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" asp-page-handler="UpdateShoppingList">
                <div class="modal-header">
                    <h5 class="modal-title" id="updateShoppingListModalLabel">Update Shopping List</h5>
                    <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="updateShoppingListName" class="form-label">Name</label>
                        <input type="text" class="form-control input-dark" id="updateShoppingListName" name="name" autocomplete="off" value="@Model.Name">
                    </div>
                    <input type="hidden" name="id" id="updateShoppingListId" value="@Model.Id"/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-dark">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>