src/Web/Pages/Operations.cshtml.cs
using ApplicationServices;
using ApplicationServices.Operations;
using Identity.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Operations.Dtos;
using Operations.Entities;
using Operations.Interfaces;
using Operations.Logic.Cards;
using Operations.Logic.Incomes;
using Operations.Logic.Payments;

namespace Web.Pages;

[Authorize]
public class OperationsModel : PageModel
{
    private readonly IOperationsService _operationsService;

    public OperationsModel(IOperationsService operationsService)
    {
        _operationsService = operationsService;
    }

    public List<Card> AllCards { get; private set; }
    
    public List<Guid> CheckedCardIds { get; private set; }
    
    public Dictionary<Guid, string> CardNames { get; set; }
    
    public int Sum { get; set; }
    
    public List<IOperation> Operations { get; private set; }

    public async Task<IActionResult> OnGet()
    {
        var userCards = await _operationsService.GetAllUserCards(User);
        var operations = await _operationsService.GetAllUserOperations(User);

        AllCards = userCards.OrderBy(card => card.Name).ToList();
        CheckedCardIds = AllCards.Select(card => card.Id).ToList();
        CardNames = AllCards.ToDictionary(card => card.Id, card => card.Name);
        Sum = AllCards.Where(card => CheckedCardIds.Contains(card.Id)).Select(card => card.Balance).Sum();
        Operations = operations.OrderByDescending(operation => operation.DateTime).ToList();

        return Page();
    }
    
    public async Task<IActionResult> OnPost(List<Guid> cardIds)
    {
        var userCards = await _operationsService.GetAllUserCards(User);
        var operations = await _operationsService.GetUserOperationsByCardIds(User, cardIds);

        AllCards = userCards.OrderBy(card => card.Name).ToList();
        CheckedCardIds = cardIds;
        CardNames = AllCards.ToDictionary(card => card.Id, card => card.Name);
        Sum = AllCards.Where(card => CheckedCardIds.Contains(card.Id)).Select(card => card.Balance).Sum();
        Operations = operations.OrderByDescending(operation => operation.DateTime).ToList();

        return Page();
    }

    public async Task<IActionResult> OnPostPayment(CreatePaymentDto dto)
    {
        await _operationsService.CreatePayment(User, dto);

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostIncome(CreateIncomeDto dto)
    {
        await _operationsService.CreateIncome(User, dto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostUpdatePayment(UpdatePaymentDto dto)
    {
        await _operationsService.UpdatePayment(User, dto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostUpdateIncome(UpdateIncomeDto dto)
    {
        await _operationsService.UpdateIncome(User, dto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostDeletePayment(Guid id)
    {
        await _operationsService.DeletePayment(User, id);

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostDeleteIncome(Guid id)
    {
        await _operationsService.DeleteIncome(User, id);

        return RedirectToPage();
    }
}

src/Web/Pages/Operations/Index.cshtml.cs
using ApplicationServices.Operations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Operations.Dtos;
using Operations.Entities;
using Operations.Interfaces;

namespace Web.Pages.Operations;

[Authorize]
public class IndexModel : PageModel
{
    private readonly IOperationsService _operationsService;

    public IndexModel(IOperationsService operationsService)
    {
        _operationsService = operationsService;
    }

    public List<Card> AllCards { get; private set; }
    
    public List<Guid> CheckedCardIds { get; private set; }
    
    public Dictionary<Guid, string> CardNames { get; set; }
    
    public decimal Sum { get; set; }
    
    public List<IOperation> Operations { get; private set; }

    public async Task<IActionResult> OnGet()
    {
        var userCards = await _operationsService.GetAllUserCards(User);
        var operations = await _operationsService.GetAllUserOperations(User);

        AllCards = userCards?.OrderBy(card => card.Name).ToList();
        CheckedCardIds = AllCards?.Select(card => card.Id).ToList();
        CardNames = AllCards?.ToDictionary(card => card.Id, card => card.Name);
        Sum = AllCards is not null ? 
            AllCards.Where(card => CheckedCardIds.Contains(card.Id)).Select(card => card.Balance).Sum() : 0;
        Operations = operations?.OrderByDescending(operation => operation.DateTime).ToList();

        return Page();
    }
    
    public async Task<IActionResult> OnPost(List<Guid> cardIds)
    {
        var userCards = await _operationsService.GetAllUserCards(User);
        var operations = await _operationsService.GetUserOperationsByCardIds(User, cardIds);

        AllCards = userCards?.OrderBy(card => card.Name).ToList();
        CheckedCardIds = cardIds;
        CardNames = AllCards?.ToDictionary(card => card.Id, card => card.Name);
        Sum = AllCards is not null ? 
            AllCards.Where(card => CheckedCardIds.Contains(card.Id)).Select(card => card.Balance).Sum() : 0;
        Operations = operations?.OrderByDescending(operation => operation.DateTime).ToList();

        return Page();
    }

    public async Task<IActionResult> OnPostPayment(CreatePaymentDto dto)
    {
        await _operationsService.CreatePayment(User, dto);

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostIncome(CreateIncomeDto dto)
    {
        await _operationsService.CreateIncome(User, dto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostUpdatePayment(UpdatePaymentDto dto)
    {
        await _operationsService.UpdatePayment(User, dto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostUpdateIncome(UpdateIncomeDto dto)
    {
        await _operationsService.UpdateIncome(User, dto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostDeletePayment(Guid id)
    {
        await _operationsService.DeletePayment(User, id);

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostDeleteIncome(Guid id)
    {
        await _operationsService.DeleteIncome(User, id);

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostTransfer(TransferDto dto)
    {
        await _operationsService.Transfer(User, dto);

        return RedirectToPage();
    }
}

src/Web/Pages/Operations/Regular/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages.Operations.Regular;

public class IndexModel : PageModel
{
    public void OnGet()
    {
        
    }
}

src/Web/Pages/Operations/Single/Index.cshtml.cs
using ApplicationServices.Operations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Operations.Dtos;
using Operations.Dtos.IncomeRecords;
using Operations.Dtos.PaymentRecords;
using Operations.Entities;
using Operations.Interfaces;

namespace Web.Pages.Operations.Single;

[Authorize]
public class IndexModel : PageModel
{
    private readonly IOperationsService _operationsService;

    public IndexModel(IOperationsService operationsService)
    {
        _operationsService = operationsService;
    }

    public List<Card> AllCards { get; private set; }
    
    public List<Guid> CheckedCardIds { get; private set; }
    
    public Dictionary<Guid, string> CardNames { get; set; }
    
    public int Sum { get; set; }
    
    public List<IOperationRecord> Operations { get; private set; }

    public async Task<IActionResult> OnGet()
    {
        var userCards = await _operationsService.GetAllUserCards(User);
        var operations = await _operationsService.GetAllUserOperations(User);

        AllCards = userCards?.OrderBy(card => card.Name).ToList();
        CheckedCardIds = AllCards?.Select(card => card.Id).ToList();
        CardNames = AllCards?.ToDictionary(card => card.Id, card => card.Name);
        Sum = AllCards is not null ? 
            AllCards.Where(card => CheckedCardIds.Contains(card.Id)).Select(card => card.Balance).Sum() : 0;
        Operations = operations?.OrderByDescending(operation => operation.DateTime).ToList();

        return Page();
    }
    
    public async Task<IActionResult> OnPost(List<Guid> cardIds)
    {
        var userCards = await _operationsService.GetAllUserCards(User);
        var operations = await _operationsService.GetUserOperationsByCardIds(User, cardIds);

        AllCards = userCards?.OrderBy(card => card.Name).ToList();
        CheckedCardIds = cardIds;
        CardNames = AllCards?.ToDictionary(card => card.Id, card => card.Name);
        Sum = AllCards is not null ? 
            AllCards.Where(card => CheckedCardIds.Contains(card.Id)).Select(card => card.Balance).Sum() : 0;
        Operations = operations?.OrderByDescending(operation => operation.DateTime).ToList();

        return Page();
    }

    public async Task<IActionResult> OnPostPayment(CreatePaymentRecordDto recordDto)
    {
        await _operationsService.CreatePayment(User, recordDto);

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostIncome(CreateIncomeRecordDto recordDto)
    {
        await _operationsService.CreateIncome(User, recordDto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostUpdatePayment(UpdatePaymentRecordDto recordDto)
    {
        await _operationsService.UpdatePayment(User, recordDto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostUpdateIncome(UpdateIncomeRecordDto recordDto)
    {
        await _operationsService.UpdateIncome(User, recordDto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostDeletePayment(Guid id)
    {
        await _operationsService.DeletePayment(User, id);

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostDeleteIncome(Guid id)
    {
        await _operationsService.DeleteIncome(User, id);

        return RedirectToPage();
    }
}

src/Web/Pages/Operations/AddIncomePartial.cshtml
@using Card = global::Operations.Entities.Card
@model List<Card>

<div class="modal fade" id="addIncomeModal" tabindex="-1" aria-labelledby="addIncomeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" asp-page-handler="Income">
                <div class="modal-header">
                    <h5 class="modal-title" id="addIncomeModalLabel">Add Income</h5>
                    <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="incomeNameLabel" class="form-label">Name</label>
                        <input type="text" class="form-control input-dark" id="incomeNameLabel" name="name" autocomplete="off">
                    </div>
                    <div class="mb-3">
                        <label for="incomeAmountLabel" class="form-label">Amount</label>
                        <input type="number" class="form-control input-dark" id="incomeAmountLabel" name="amount" autocomplete="off" step="0.01" min="0">
                    </div>
                    
                    <div class="dropdown mb-3">
                        @* ReSharper disable once Html.IdDuplication *@
                        <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdownMenuClickableInside" data-bs-auto-close="outside">
                            Select cards
                        </button>
                        <div class="dropdown-menu p-2">
                            @foreach (var card in Model)
                            {
                                <div class="mb-1">
                                    <div class="form-check form-check-inline">
                                        <input type="radio" class="form-check-input checkbox-dark" id="card" name="cardId" value="@card.Id">
                                        <label class="form-check-label" for="card">
                                            @card.Name, balance: @card.Balance
                                        </label>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-dark">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

src/Web/Pages/Operations/AddPaymentPartial.cshtml
@using Card = global::Operations.Entities.Card
@model List<Card>

<div class="modal fade" id="addPaymentModal" tabindex="-1" aria-labelledby="addPaymentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" asp-page-handler="Payment">
                <div class="modal-header">
                    <h5 class="modal-title" id="addPaymentModalLabel">Add Payment</h5>
                    <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="paymentNameLabel" class="form-label">Name</label>
                        <input type="text" class="form-control input-dark" id="paymentNameLabel" name="name" autocomplete="off">
                    </div>
                    <div class="mb-3">
                        <label for="paymentAmountLabel" class="form-label">Amount</label>
                        <input type="number" class="form-control input-dark" id="paymentAmountLabel" name="amount" autocomplete="off" step="0.01" min="0">
                    </div>
                    
                    <div class="dropdown mb-3">
                        @* ReSharper disable once Html.IdDuplication *@
                        <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdownMenuClickableInside" data-bs-auto-close="outside">
                            Select cards
                        </button>
                        <div class="dropdown-menu p-2">
                                @foreach (var card in Model)
                                {
                                    <div class="mb-1">
                                        <div class="form-check form-check-inline">
                                            <input type="radio" class="form-check-input checkbox-dark" id="card" name="cardId" value="@card.Id">
                                            <label class="form-check-label" for="card">
                                                @card.Name, balance: @card.Balance
                                            </label>
                                        </div>
                                    </div>
                                }
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-dark">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

src/Web/Pages/Operations/Index.cshtml
@page
@using global::Operations.Entities
@model IndexModel

@{
    ViewData["Title"] = "Operations";
}

<div class="h4">Sum: @Model.Sum ₽</div>
<div class="row g-2 row-cols-auto">
    <div class="col">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#addPaymentModal">
            Add Payment
        </button>
    </div>
    <div class="col">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#addIncomeModal">
            Add Income
        </button>
    </div>
    <div class="col">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#transferModal">
            Transfer
        </button>
    </div>
    <div class="dropdown col-4">
        @* ReSharper disable once Html.IdDuplication *@
        <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdownMenuClickableInside" data-bs-auto-close="outside">
            Select cards
        </button>
        <div class="dropdown-menu">
            <form class="px-2 py-2" method="POST">
                @foreach (var card in Model.AllCards)
                {
                    <div class="mb-1">
                        <div class="form-check form-check-inline">
                            @if (Model.CheckedCardIds.Contains(card.Id))
                            {
                                <input type="checkbox" class="form-check-input checkbox-dark" id="card" name="cardIds" value="@card.Id" checked>
                            }
                            else
                            {
                                <input type="checkbox" class="form-check-input checkbox-dark" id="card" name="cardIds" value="@card.Id">
                            }
                            <label class="form-check-label" for="card">
                                @card.Name, balance: @card.Balance
                            </label>
                        </div>
                    </div>
                }
                <button type="submit" class="btn btn-dark">Load</button>
            </form>
        </div>
    </div>
</div>

<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">Type</th>
        <th scope="col">Date</th>
        <th scope="col">Name</th>
        <th scope="col">Amount</th>
        <th scope="col">Card</th>
        <th scope="col">Manage</th>
    </tr>
    </thead>
    <tbody class="table-group-divider">
    @foreach (var operation in Model.Operations)
    {
        @if (operation is Payment payment)
        {
            <tr>
                <th class="col-1" scope="row">-</th>
                <td class="col-2">@payment.DateTime.ToShortDateString()</td>
                <td class="col-3">@payment.Name</td>
                <td class="col-2">@payment.Amount ₽</td>
                <td class="col-2">@Model.CardNames[payment.CardId]</td>
                <td class="col-2">
                    <form method="POST">
                        <button type="button" class="btn-link" data-bs-toggle="modal" data-bs-target="#@string.Concat("id", payment.Id)">Update</button>
                        <button type="submit" class="btn-link" asp-page-handler="DeletePayment" asp-route-id="@payment.Id">Delete</button>
                    </form>
                </td>
            </tr>
            <div class="modal fade" id="@string.Concat("id", payment.Id)" tabindex="-1" aria-labelledby="updatePaymentModalLabel" aria-hidden="true">
                <partial name="UpdatePaymentPartial" model="@(Model.AllCards, payment)"/>
            </div>
        }
        else if (operation is Income income)
        {
            <tr class="table-success">
                <th class="col-1" scope="row">+</th>
                <td class="col-2">@income.DateTime</td>
                <td class="col-3">@income.Name</td>
                <td class="col-2">@income.Amount ₽</td>
                <td class="col-2">@Model.CardNames[income.CardId]</td>
                <td class="col-2">
                    <form method="POST">
                        <button type="button" class="btn-link" data-bs-toggle="modal" data-bs-target="#@string.Concat("id", income.Id)">Update</button>
                        <button type="submit" class="btn-link" asp-page-handler="DeleteIncome" asp-route-id="@income.Id">Delete</button>
                    </form>
                </td>
            </tr>
            <div class="modal fade" id="@string.Concat("id", income.Id)" tabindex="-1" aria-labelledby="updateIncomeModalLabel" aria-hidden="true">
                <partial name="UpdateIncomePartial" model="@(Model.AllCards, income)"/>
            </div>
        }
    }
    </tbody>
</table>

<!-- Add Payment Modal -->
<partial name="AddPaymentPartial" model="@Model.AllCards"/>

<!-- Add Income Modal -->
<partial name="AddIncomePartial" model="@Model.AllCards"/>

<!-- Transfer Modal -->
<partial name="TransferPartial" model="@Model.AllCards"/>

src/Web/Pages/Operations/TransferPartial.cshtml
@using Card = global::Operations.Entities.Card
@model List<Card>

<div class="modal fade" id="transferModal" tabindex="-1" aria-labelledby="transferModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" asp-page-handler="Transfer">
                <div class="modal-header">
                    <h5 class="modal-title" id="transferModalLabel">Transfer</h5>
                    <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="transferNameLabel" class="form-label">Name</label>
                        <input type="text" class="form-control input-dark" id="transferNameLabel" name="name" autocomplete="off">
                    </div>
                    <div class="mb-3">
                        <label for="transferAmountLabel" class="form-label">Amount</label>
                        <input type="number" class="form-control input-dark" id="transferAmountLabel" name="amount" autocomplete="off" step="0.01" min="0">
                    </div>
                    
                    <div class="dropdown mb-3">
                        @* ReSharper disable once Html.IdDuplication *@
                        <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdownMenuClickableInside" data-bs-auto-close="outside">
                            Select cards
                        </button>
                        <div class="dropdown-menu p-2">
                            @foreach (var card in Model)
                            {
                                <div class="mb-1">
                                    <div class="form-check form-check-inline">
                                        <input type="radio" class="form-check-input checkbox-dark" id="card" name="fromCardId" value="@card.Id">
                                        <label class="form-check-label" for="card">
                                            @card.Name, balance: @card.Balance
                                        </label>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    
                    <div class="dropdown mb-3">
                        @* ReSharper disable once Html.IdDuplication *@
                        <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdownMenuClickableInside" data-bs-auto-close="outside">
                            Select cards
                        </button>
                        <div class="dropdown-menu p-2">
                            @foreach (var card in Model)
                            {
                                <div class="mb-1">
                                    <div class="form-check form-check-inline">
                                        <input type="radio" class="form-check-input checkbox-dark" id="card" name="toCardId" value="@card.Id">
                                        <label class="form-check-label" for="card">
                                            @card.Name, balance: @card.Balance
                                        </label>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-dark">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

src/Web/Pages/Operations/UpdateIncomePartial.cshtml
@using Card = global::Operations.Entities.Card
@using Income = global::Operations.Entities.Income
@model (List<Card>, Income)

<div class="modal-dialog">
    <div class="modal-content">
        <form method="POST" asp-page-handler="UpdateIncome">
            <div class="modal-header">
                <h5 class="modal-title" id="updateIncomeModalLabel">Update Income</h5>
                <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="updateIncomeName" class="form-label">Name</label>
                    <input type="text" class="form-control input-dark" id="updateIncomeName" name="name" autocomplete="off" value="@Model.Item2.Name">
                </div>
                <div class="mb-3">
                    <label for="incomeAmountLabel" class="form-label">Amount</label>
                    <input type="number" class="form-control input-dark" id="incomeAmountLabel" name="amount" autocomplete="off" step="0.01" min="0" value="@Model.Item2.Amount">
                </div>

                <div class="dropdown mb-3">
                    @* ReSharper disable once Html.IdDuplication *@
                    <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdownMenuClickableInside" data-bs-auto-close="outside">
                        Select cards
                    </button>
                    <div class="dropdown-menu p-2">
                        @foreach (var card in Model.Item1)
                        {
                            <div class="mb-1">
                                <div class="form-check form-check-inline">
                                    @if (card.Id == Model.Item2.CardId)
                                    {
                                        <input type="radio" class="form-check-input checkbox-dark" id="card" name="cardId" value="@card.Id" checked>
                                    }
                                    else
                                    {
                                        <input type="radio" class="form-check-input checkbox-dark" id="card" name="cardId" value="@card.Id">
                                    }
                                    <label class="form-check-label" for="card">
                                        @card.Name, balance: @card.Balance
                                    </label>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <input type="hidden" name="id" id="updateIncomeId" value="@Model.Item2.Id"/>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-dark">Save</button>
            </div>
        </form>
    </div>
</div>

src/Web/Pages/Operations/UpdatePaymentPartial.cshtml
@using Card = global::Operations.Entities.Card
@using Payment = global::Operations.Entities.Payment
@model (List<Card>, Payment)

<div class="modal-dialog">
    <div class="modal-content">
        <form method="POST" asp-page-handler="UpdatePayment">
            <div class="modal-header">
                <h5 class="modal-title" id="updatePaymentModalLabel">Update Payment</h5>
                <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="updatePaymentName" class="form-label">Name</label>
                    <input type="text" class="form-control input-dark" id="updatePaymentName" name="name" autocomplete="off" value="@Model.Item2.Name">
                </div>
                <div class="mb-3">
                    <label for="paymentAmountLabel" class="form-label">Amount</label>
                    <input type="number" class="form-control input-dark" id="paymentAmountLabel" name="amount" autocomplete="off" step="0.01" min="0" value="@Model.Item2.Amount">
                </div>

                <div class="dropdown mb-3">
                    @* ReSharper disable once Html.IdDuplication *@
                    <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdownMenuClickableInside" data-bs-auto-close="outside">
                        Select cards
                    </button>
                    <div class="dropdown-menu p-2">
                        @foreach (var card in Model.Item1)
                        {
                            <div class="mb-1">
                                <div class="form-check form-check-inline">
                                    @if (card.Id == Model.Item2.CardId)
                                    {
                                        <input type="radio" class="form-check-input checkbox-dark" id="card" name="cardId" value="@card.Id" checked>
                                    }
                                    else
                                    {
                                        <input type="radio" class="form-check-input checkbox-dark" id="card" name="cardId" value="@card.Id">
                                    }
                                    <label class="form-check-label" for="card">
                                        @card.Name, balance: @card.Balance
                                    </label>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <input type="hidden" name="id" id="updatePaymentId" value="@Model.Item2.Id"/>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-dark">Save</button>
            </div>
        </form>
    </div>
</div>