src/Web/Pages/Account/Index.cshtml.cs
using ApplicationServices.Identity;
using ApplicationServices.Operations;
using Identity.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Operations.Dtos;
using Operations.Entities;

namespace Web.Pages.Account;

public class IndexModel : PageModel
{
    private readonly IIdentityService _identityService;
    private readonly IOperationsService _operationsService;

    public IndexModel(IIdentityService identityService, IOperationsService operationsService)
    {
        _identityService = identityService;
        _operationsService = operationsService;
    }

    public User Profile { get; set; }
    
    public List<Card> Cards { get; set; }

    public async Task<IActionResult> OnGet()
    {
        var user = await _identityService.GetUser(User);
        var cards = await _operationsService.GetAllUserCards(User);
        
        Profile = user;
        Cards = cards?.OrderBy(card => card.Name).ToList();
        
        return Page();
    }

    public async Task<IActionResult> OnPostAddCard(CreateCardDto dto)
    {
        await _operationsService.CreateCard(User, dto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostUpdateCard(UpdateCardDto dto)
    {
        await _operationsService.UpdateCard(User, dto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostDeleteCard(Guid id)
    {
        await _operationsService.DeleteCard(User, id);

        return RedirectToPage();
    }
}

src/Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages;

[AllowAnonymous]
[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

src/Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages;

[AllowAnonymous]
public class Index : PageModel
{
    public void OnGet()
    {
        
    }
}

src/Web/Pages/Operations.cshtml.cs
using ApplicationServices;
using ApplicationServices.Operations;
using Identity.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Operations.Dtos;
using Operations.Entities;
using Operations.Interfaces;
using Operations.Logic.Cards;
using Operations.Logic.Incomes;
using Operations.Logic.Payments;

namespace Web.Pages;

[Authorize]
public class OperationsModel : PageModel
{
    private readonly IOperationsService _operationsService;

    public OperationsModel(IOperationsService operationsService)
    {
        _operationsService = operationsService;
    }

    public List<Card> AllCards { get; private set; }
    
    public List<Guid> CheckedCardIds { get; private set; }
    
    public Dictionary<Guid, string> CardNames { get; set; }
    
    public int Sum { get; set; }
    
    public List<IOperation> Operations { get; private set; }

    public async Task<IActionResult> OnGet()
    {
        var userCards = await _operationsService.GetAllUserCards(User);
        var operations = await _operationsService.GetAllUserOperations(User);

        AllCards = userCards.OrderBy(card => card.Name).ToList();
        CheckedCardIds = AllCards.Select(card => card.Id).ToList();
        CardNames = AllCards.ToDictionary(card => card.Id, card => card.Name);
        Sum = AllCards.Where(card => CheckedCardIds.Contains(card.Id)).Select(card => card.Balance).Sum();
        Operations = operations.OrderByDescending(operation => operation.DateTime).ToList();

        return Page();
    }
    
    public async Task<IActionResult> OnPost(List<Guid> cardIds)
    {
        var userCards = await _operationsService.GetAllUserCards(User);
        var operations = await _operationsService.GetUserOperationsByCardIds(User, cardIds);

        AllCards = userCards.OrderBy(card => card.Name).ToList();
        CheckedCardIds = cardIds;
        CardNames = AllCards.ToDictionary(card => card.Id, card => card.Name);
        Sum = AllCards.Where(card => CheckedCardIds.Contains(card.Id)).Select(card => card.Balance).Sum();
        Operations = operations.OrderByDescending(operation => operation.DateTime).ToList();

        return Page();
    }

    public async Task<IActionResult> OnPostPayment(CreatePaymentDto dto)
    {
        await _operationsService.CreatePayment(User, dto);

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostIncome(CreateIncomeDto dto)
    {
        await _operationsService.CreateIncome(User, dto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostUpdatePayment(UpdatePaymentDto dto)
    {
        await _operationsService.UpdatePayment(User, dto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostUpdateIncome(UpdateIncomeDto dto)
    {
        await _operationsService.UpdateIncome(User, dto);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostDeletePayment(Guid id)
    {
        await _operationsService.DeletePayment(User, id);

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostDeleteIncome(Guid id)
    {
        await _operationsService.DeleteIncome(User, id);

        return RedirectToPage();
    }
}

src/Web/Pages/SignIn.cshtml.cs
using Identity.Dtos;
using Identity.Entities;
using Identity.Logic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages;

[AllowAnonymous]
public class SignInModel : PageModel
{
    private readonly SignInManager<User> _signInManager;
    private readonly IAccountService _accountService;

    public SignInModel(SignInManager<User> signInManager, IAccountService accountService)
    {
        _signInManager = signInManager;
        _accountService = accountService;
    }
    
    public string ErrorMessage { get; private set; }

    public IActionResult OnGet()
    {
        if (_signInManager.IsSignedIn(User))
            return RedirectToPage("Profile");

        return Page();
    }

    public async Task<IActionResult> OnPost(SignInDto dto)
    {
        if (_signInManager.IsSignedIn(User))
            return RedirectToPage("Profile");
        
        var result = await _accountService.SignIn(dto);
        if (result.Succeeded)
        {
            return RedirectToPage("Profile");
        }

        ErrorMessage = "Invalid login attempt";
        return Page();
    }
}

src/Web/Pages/SignOut.cshtml.cs
using Identity.Entities;
using Identity.Logic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages;

public class SignOutModel : PageModel
{
    private readonly SignInManager<User> _signInManager;
    private readonly IAccountService _accountService;
    
    public SignOutModel(SignInManager<User> signInManager, IAccountService accountService)
    {
        _signInManager = signInManager;
        _accountService = accountService;
    }
    
    public async Task<IActionResult> OnGet()
    {
        if (_signInManager.IsSignedIn(User))
            await _accountService.SignOut();
            
        return RedirectToPage("Index");
    }
}

src/Web/Pages/SignUp.cshtml.cs
using Identity.Dtos;
using Identity.Entities;
using Identity.Logic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages;

[AllowAnonymous]
public class SignUpModel : PageModel
{
    
    private readonly SignInManager<User> _signInManager;
    private readonly IAccountService _accountService;

    public SignUpModel(SignInManager<User> signInManager, IAccountService accountService)
    {
        _signInManager = signInManager;
        _accountService = accountService;
    }

    public IActionResult OnGet()
    {
        if (_signInManager.IsSignedIn(User))
            return RedirectToPage("Profile");

        return Page();
    }

    public async Task<IActionResult> OnPost(SignUpDto dto)
    {
        if (_signInManager.IsSignedIn(User))
            return RedirectToPage("Profile");
        
        var user = await _accountService.SignUp(dto);
        if (user is not null)
        {
            await _signInManager.SignInAsync(user, true);
            return RedirectToPage("Profile");
        }
        
        return Page();
    }

    public async Task<IActionResult> OnGetUnique(string login)
    {
        var isUnique = await _accountService.IsLoginUnique(login);

        return Content(isUnique.ToString());
    }
}

src/Web/Pages/Index.cshtml
@page
@model Web.Pages.Index

@{
    ViewData["Title"] = "Moneys";
}

Hello World!

src/Web/Pages/Profile.cshtml
@page
@model Web.Pages.ProfileModel

@{
    ViewData["Title"] = "Profile";
}

<div class="p-2">
    <div class="h4">User: @Model.Profile.UserName</div>
    <hr/>
</div>
<div class="d-flex">
    <div class="p-2">
        <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#addCardModal">
            Add card
        </button>
    </div>
</div>
<div class="d-flex flex-wrap">
    @foreach (var card in Model.Cards)
    {
        <div class="p-2">
            <div class="card border-dark mb-3" style="width: 18rem;">
                <div class="card-header">@card.Name</div>
                <div class="card-body">
                    <h5 class="card-title">@card.Balance</h5>
                    <form method="POST">
                        <button type="button" class="btn-link card-link" onclick="updateCard('@card.Name', '@card.Id')" data-bs-toggle="modal" data-bs-target="#updateCardModal">Update</button>
                        <button type="submit" class="btn-link card-link" asp-page-handler="DeleteCard" asp-route-id="@card.Id">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    }
</div>

<!-- Add Card Modal -->
<div class="modal fade" id="addCardModal" tabindex="-1" aria-labelledby="addCardModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" asp-page-handler="AddCard">
                <div class="modal-header">
                    <h5 class="modal-title" id="addCardModalLabel">Add card</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="addCardName" class="form-label">Name</label>
                        <input type="text" class="form-control input-dark" id="addCardName" name="name" autocomplete="off">
                    </div>
                    <div class="mb-3">
                        <label for="startBalance" class="form-label">Start balance</label>
                        <input type="number" class="form-control input-dark" id="startBalance" name="startBalance" autocomplete="off">
                    </div>
                </div>
                <input type="hidden" name="id">
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-dark">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Update Card Modal -->
<div class="modal fade" id="updateCardModal" tabindex="-1" aria-labelledby="updateCardModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" asp-page-handler="UpdateCard">
                <div class="modal-header">
                    <h5 class="modal-title" id="updateCardModalLabel">Update card</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="updateCardName" class="form-label">Name</label>
                        <input type="text" class="form-control input-dark" id="updateCardName" name="name" autocomplete="off">
                    </div>
                </div>
                <input type="hidden" name="id" id="updateCardId">
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-dark">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
let updateCard = function (cardName, cardId) {
    document.getElementById("updateCardName").value = cardName;
    document.getElementById("updateCardId").value = cardId;
}
</script>

src/Web/Pages/SignIn.cshtml
@page
@model Web.Pages.SignInModel

@{
    ViewData["Title"] = "Sign In";
}

<div class="d-flex justify-content-center align-items-center">
    <form method="POST">
        <div class="mb-3">
            <label for="login" class="form-label">Login</label>
            <input type="text" class="form-control input-dark" id="login" name="login" autocomplete="off">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control input-dark" id="password" name="password" autocomplete="off">
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input input-dark" id="check">
            <label class="form-check-label" for="check" name="remember">Check me out</label>
        </div>
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
</div>

src/Web/Pages/SignUp.cshtml
@page
@model Web.Pages.SignUpModel

@{
    ViewData["Title"] = "Sign Up";
}

<div class="d-flex justify-content-center align-items-center">
    <form method="POST" id="signUpForm">
        <div class="mb-3">
            <label for="login" class="form-label">Login</label>
            <input type="text" class="form-control input-dark" id="login" name="login" autocomplete="off" aria-describedby="loginMessage" required>
            <div id="loginMessage" class="invalid-feedback">
                This login is already used
            </div>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control input-dark" id="password" name="password" autocomplete="off" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control input-dark" id="repeatPassword" autocomplete="off" aria-describedby="passwordMessage" required>
            <div id="repeatPasswordMessage" class="invalid-feedback">
                Passwords doesn't match
            </div>
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input input-dark" id="check">
            <label class="form-check-label" for="check" name="remember">Check me out</label>
        </div>
        <button id="signUpButton" type="button" class="btn btn-dark">Submit</button>
    </form>
</div>

<script>
let form = document.getElementById("signUpForm");
let button = document.getElementById("signUpButton");

button.onclick = async function() {
    let login = document.getElementById("login")
    let password = document.getElementById("password");
    let repeatPassword = document.getElementById("repeatPassword");
    
    if (password.value !== repeatPassword.value) 
    {
        password.classList.add("is-invalid");
        repeatPassword.classList.add("is-invalid");  
        return false;
    }
        
    let response = await fetch("/SignUp?handler=Unique&login=" + login.value)
    let isUniqueLogin = await response.text()
    console.log(isUniqueLogin);
    if (isUniqueLogin === "False")
    {
        login.classList.add("is-invalid");
        return false;        
    }
    
    form.submit();
}
</script>